name: joe-username
on:
  schedule: # Run workflow automatically
    - cron: '0/20 * * * *' # Runs every 20 mins.
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update this repo's README with random joe-username
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: python-setup
        uses: actions/setup-python@v2     
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: build README
        run: python joe-username/joe-username.py
      - name: Commit and push if README changed
        run: |-
          git diff
          git config --global user.email "readme-bot@example.com"
          git config --global user.name "README-bot"
          git diff --quiet || (git add README.md && git commit -m "Updated README")
          git push
